version: "2"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "app"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - "./dev-ops/var/data/mysql:/var/lib/mysql"
      - "./dev-ops/mysql/conf:/etc/mysql/conf.d"
    networks:
      - default